version: '3.9'
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - compose-bridge
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - compose-bridge
    depends_on: 
      - backend
networks:
  compose-bridge:
    driver: bridge